import math

ITERATIONS      	 	= 1000
MOTOR_STRENGTH  	 	= 30

AMPLITUDE_BACK_LEG 	 	= math.pi/4
FREQUENCY_BACK_LEG 	 	= 8
PHASE_OFFSET_BACK_LEG  	= 5

AMPLITUDE_FRONT_LEG 	= math.pi/4
FREQUENCY_FRONT_LEG 	= 8
PHASE_OFFSET_FRONT_LEG 	= 5

SENSOR_VALUES 			= "data/sensor_values.npy"
MOTOR_VALUES 			= "data/motor_values.npy"

NUMBER_OF_GENERATIONS	= 2000